# Generated by Django 3.1.14 on 2025-09-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gargoyle", "0002_bytes_to_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switch",
            name="value",
            field=models.JSONField(default=dict),
        ),
    ]
